// apps/api/test/integration/helpers/coverage-matrix.ts
import { readFileSync, readdirSync, writeFileSync, existsSync, mkdirSync } from 'node:fs';
import { join, relative } from 'node:path';

export interface WriteCoverageMatrixArgs {
  integrationDir: string;
  algorithmDoc: string;
  outFile: string;
}

interface Annotation { id: string; file: string; line: number; }

export async function writeCoverageMatrix(args: WriteCoverageMatrixArgs): Promise<void> {
  const ids = parseAlgorithmIds(args.algorithmDoc);          // ['A-01', …, 'I-03']
  const found = scanAnnotations(args.integrationDir);        // [{ id: 'A-01', file, line }]

  const seen = new Map<string, Annotation>();
  for (const ann of found) seen.set(ann.id, ann);

  const rows = ids.map((id) => {
    const a = seen.get(id);
    if (!a) return `| ${id} | — pending | — | — |`;
    return `| ${id} | covered | ${a.file} | ${a.line} |`;
  });

  const unknown = found
    .filter((a) => !ids.includes(a.id))
    .map((a) => `| ${a.id} (NOT IN ALGORITHM) | drift | ${a.file} | ${a.line} |`);

  const outDir = args.outFile.substring(0, Math.max(args.outFile.lastIndexOf('/'), args.outFile.lastIndexOf('\\')));
  if (!existsSync(outDir)) mkdirSync(outDir, { recursive: true });

  writeFileSync(
    args.outFile,
    [
      '# Algorithm §Part 4 Test Coverage Matrix',
      '',
      '> Auto-generated by `apps/api/test/integration/helpers/coverage-matrix.ts` on every `test:integration` run. Do not edit by hand.',
      '',
      '| algorithm test | status | spec file | line |',
      '|----------------|--------|-----------|------|',
      ...rows,
      ...unknown,
      '',
    ].join('\n'),
  );

  if (unknown.length > 0) {
    throw new Error(
      `Coverage matrix drift: annotations reference IDs not in algorithm doc: ${unknown.join(', ')}`,
    );
  }
}

function parseAlgorithmIds(filePath: string): string[] {
  if (!existsSync(filePath)) {
    // Algorithm doc not found — return empty (teardown should not hard-fail CI)
    return [];
  }
  const text = readFileSync(filePath, 'utf-8');
  const re = /^\|\s*([A-I]-\d{2})\s*\|/gm;
  const ids: string[] = [];
  let m: RegExpExecArray | null;
  while ((m = re.exec(text))) ids.push(m[1]);
  return Array.from(new Set(ids)).sort();
}

function scanAnnotations(rootDir: string): Annotation[] {
  const out: Annotation[] = [];
  if (!existsSync(rootDir)) return out;
  walk(rootDir, (file, full) => {
    if (!file.endsWith('.integration.spec.ts')) return;
    const lines = readFileSync(full, 'utf-8').split('\n');
    lines.forEach((line, i) => {
      const m = line.match(/\/\/\s*@algorithm:\s*([A-I]-\d{2})/);
      if (m) out.push({ id: m[1], file: relative(rootDir, full).replace(/\\/g, '/'), line: i + 1 });
    });
  });
  return out;
}

function walk(dir: string, cb: (name: string, full: string) => void): void {
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    const full = join(dir, entry.name);
    if (entry.isDirectory()) walk(full, cb);
    else cb(entry.name, full);
  }
}
