server {
  listen 8080;
  root /usr/share/nginx/html;
  index index.html;
  location / {
    try_files $uri $uri/ /index.html;
  }
  location = /health/live {
    return 200 '{"alive":true}';
    add_header Content-Type application/json;
  }
}
