apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - bootstrap-secrets.yaml
  - postgres
  - pgbouncer
  - redis
  - vault
  - api
  - sla-worker
  - web
  - ingress
